- route: BARRA_BALI_CENTRO_VIA_ZONA_SUL
  days: 2, 3, 4, 5, 6
  departures: 540, 625, 650, 710, 740, 820, 1000, 1200, 1300, 1700, 1850, 2000

- route: BARRA_BALI_CENTRO_VIA_L_AMARELA
  days: 2, 3, 4, 5, 6
  departures: 615, 910, 1610, 1730

- route: BARRA_BALI_CENTRO_VIA_TIJUCA
  days: 2, 3, 4, 5, 6
  departures: 730, 1600

- route: CENTRO_BARRA_BALI_VIA_ZONA_SUL
  days: 2, 3, 4, 5, 6
  departures: 1000, 1210, 1410, 1530, 1730, 1900, 2030, 2215

- route: CENTRO_BARRA_BALI_VIA_L_AMARELA
  days: 2, 3, 4, 5, 6
  departures: 640, 720, 1715, 1750, 1820, 1920

- route: CENTRO_BARRA_BALI_VIA_TIJUCA
  days: 2, 3, 4, 5, 6
  departures: 940, 1740

- route: CENTRO_BARRA_BALI_VIA_JD_BOTANICO
  days: 2, 3, 4, 5, 6
  departures: 750

- route: CIRCULAR_BARRA
  days: 2, 3, 4, 5, 6
  departures: 700, 805, 920, 1050, 1240, 1400, 1600, 1800

- route: CIRCULAR_BARRA
  days: 7
  departures: 930, 1400, 1800

- route: CIRCULAR_RECREIO
  days: 2, 3, 4, 5, 6
  departures: 630, 1245

- route: CIRCULAR_RECREIO
  days: 7
  departures: 1130, 1600
