package com.example.felipe.catchthatbus.departures

enum class BusRoute {
    BARRA_BALI_CENTRO_VIA_ZONA_SUL,
    BARRA_BALI_CENTRO_VIA_L_AMARELA,
    BARRA_BALI_CENTRO_VIA_TIJUCA,
    BARRA_BALI_CENTRO_VIA_ZONA_SUL_L_AMARELA_ESPECIAL,

    CENTRO_BARRA_BALI_VIA_ZONA_SUL,
    CENTRO_BARRA_BALI_VIA_L_AMARELA,
    CENTRO_BARRA_BALI_VIA_TIJUCA,
    CENTRO_BARRA_BALI_VIA_JD_BOTANICO,

    CIRCULAR_BARRA,
    CIRCULAR_RECREIO
}