package com.example.felipe.catchthatbus.model

import com.example.felipe.catchthatbus.R

enum class BusRoute(val resId: Int) {
    BARRA_BALI_CENTRO_VIA_ZONA_SUL(R.string.BARRA_BALI_CENTRO_VIA_ZONA_SUL),
    BARRA_BALI_CENTRO_VIA_L_AMARELA(R.string.BARRA_BALI_CENTRO_VIA_L_AMARELA),
    BARRA_BALI_CENTRO_VIA_TIJUCA(R.string.BARRA_BALI_CENTRO_VIA_TIJUCA),

    CENTRO_BARRA_BALI_VIA_ZONA_SUL(R.string.CENTRO_BARRA_BALI_VIA_ZONA_SUL),
    CENTRO_BARRA_BALI_VIA_L_AMARELA(R.string.CENTRO_BARRA_BALI_VIA_L_AMARELA),
    CENTRO_BARRA_BALI_VIA_TIJUCA(R.string.CENTRO_BARRA_BALI_VIA_TIJUCA),
    CENTRO_BARRA_BALI_VIA_JD_BOTANICO(R.string.CENTRO_BARRA_BALI_VIA_JD_BOTANICO),

    CIRCULAR_BARRA(R.string.CIRCULAR_BARRA),
    CIRCULAR_RECREIO(R.string.CIRCULAR_RECREIO)
}